apiVersion: skaffold/v2beta26
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
